- name: install apache and php
  tags: web
  package:
    name:
      - "{{ apache_package }}"
      - "{{ php_package }}"
    state: latest
    update_cache: yes

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: change KeepAliveTimeout
  tags: apache,ubuntu
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^KeepAliveTimeout'
    line: KeepAliveTimeout 6
  when: ansible_distribution == "Ubuntu"
  notify: restart_apache
